# Generated by Django 4.1.7 on 2023-03-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='available_rooms',
            new_name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='unavailable_rooms',
        ),
    ]
